import type { AdCampaign, AnalysisResult, BrandSettings, Product } from "@/types";

export const ownProducts: Product[] = [
  {
    id: "own-1",
    researchShared: false,
    vertical: "ecommerce",
    name: "Revital Serum",
    brand: "Lumen Lab",
    category: "Skincare",
    description: "Suero antienvejecimiento con ingredientes botánicos y ácido hialurónico.",
    benefits: ["Hidratación profunda", "Reducción de líneas finas"],
    features: ["Textura ligera", "Sin parabenos"],
    ingredients: ["Ácido hialurónico", "Vitamina E", "Extracto de aloe"],
    targetAudience: "Mujeres 25-45 interesadas en skincare premium",
    problemsSolved: ["Sequedad", "Pérdida de luminosidad"],
    objections: ["Precio", "Eficacia en piel sensible"],
    country: "España",
    language: "Español",
    price: 48,
    landingUrl: "https://example.com/revital-serum",
    images: ["/placeholder-1.svg", "/placeholder-2.svg"],
    tone: "Cálido y científico",
    status: "active",
    createdAt: "2024-06-10",
    owner: "own",
  },
  {
    id: "own-2",
    researchShared: false,
    vertical: "ecommerce",
    name: "Glow Latte",
    brand: "Lumen Lab",
    category: "Bebida funcional",
    description: "Bebida funcional con adaptógenos para recuperar energía y enfoque.",
    benefits: ["Más energía", "Mejor enfoque"],
    features: ["Sin azúcar añadida", "Ingredientes vegetales"],
    ingredients: ["Ashwagandha", "L-teanina", "Cacao"],
    targetAudience: "Profesionales que buscan equilibrio diario",
    problemsSolved: ["Fatiga", "Estrés"],
    objections: ["Efecto inmediato", "Sabor"],
    country: "México",
    language: "Español",
    price: 24,
    landingUrl: "https://example.com/glow-latte",
    images: ["/placeholder-3.svg"],
    tone: "Energetico y claro",
    status: "draft",
    createdAt: "2024-07-01",
    owner: "own",
  },
];

export const competitorProducts: Product[] = [
  {
    id: "comp-1",
    researchShared: false,
    vertical: "ecommerce",
    name: "Hydra Boost",
    brand: "Natura Glow",
    category: "Skincare",
    description: "Crema hidratante premium para piel deshidratada.",
    benefits: ["Hidratación inmediata", "Piel suave"],
    features: ["Formato crema", "Fragrance free"],
    ingredients: ["Glicerina", "Niacinamida"],
    targetAudience: "Consumidores premium de skincare",
    problemsSolved: ["Piel seca", "Sensación de tirantez"],
    objections: ["Precio", "Textura pesada"],
    country: "España",
    language: "Español",
    price: 39,
    landingUrl: "https://example.com/hydra-boost",
    images: ["/placeholder-4.svg"],
    tone: "Premium y sofisticado",
    status: "active",
    createdAt: "2024-06-14",
    owner: "competitor",
  },
  {
    id: "comp-2",
    researchShared: false,
    vertical: "ecommerce",
    name: "Focus Fuel",
    brand: "Everday",
    category: "Bebida funcional",
    description: "Bebida energética con minerales y adaptógenos.",
    benefits: ["Enfoque sostenido", "Sin crash"],
    features: ["Con cafeína natural", "Botella reciclable"],
    ingredients: ["Cafeína verde", "B12", "Ginseng"],
    targetAudience: "Trabajadores híbridos",
    problemsSolved: ["Caídas de energía", "Distracción"],
    objections: ["Sabores artificiales", "Dependencia"],
    country: "Colombia",
    language: "Español",
    price: 27,
    landingUrl: "https://example.com/focus-fuel",
    images: ["/placeholder-5.svg"],
    tone: "Dinámico y disruptivo",
    status: "active",
    createdAt: "2024-06-20",
    owner: "competitor",
  },
];

export const adsLibrary: AdCampaign[] = [
  {
    id: "ad-1",
    name: "Anuncio serum nocturno",
    brand: "Lumen Lab",
    relatedProductId: "own-1",
    type: "own",
    platform: "Instagram",
    country: "España",
    date: "2024-07-15",
    tags: ["skincare", "serum", "premium"],
    status: "analyzed",
    image: "/placeholder-1.svg",
  },
  {
    id: "ad-2",
    name: "Anuncio competitor hydration",
    brand: "Natura Glow",
    relatedProductId: "comp-1",
    type: "competitor",
    platform: "Meta Ads",
    country: "México",
    date: "2024-07-18",
    tags: ["hydration", "video", "social"],
    status: "pending",
    image: "/placeholder-4.svg",
  },
];

export const recentAnalyses: AnalysisResult[] = [
  {
    id: "analysis-1",
    title: "Análisis de anuncio Revital Serum",
    type: "analysis",
    productId: "own-1",
    productName: "Revital Serum",
    status: "completed",
    createdAt: "2024-07-20",
    summary: "Se detectó un gancho de hidratación premium y promesa de luminosidad.",
  },
  {
    id: "analysis-2",
    title: "Versión de copy Glow Latte",
    type: "copy",
    productId: "own-2",
    productName: "Glow Latte",
    status: "draft",
    createdAt: "2024-07-22",
    summary: "Texto en tono energético para Facebook Ads listo para revisar.",
  },
];

export const brandSettings: BrandSettings = {
  brandName: "Lumen Lab",
  description: "Marca de bienestar e innovación centrada en productos premium y experiencias claras.",
  logo: "/placeholder-6.svg",
  colors: {
    primary: "#7c3aed",
    secondary: "#0f172a",
  },
  voice: "Cálida, simple y autoritativa",
  recommendedWords: ["premium", "claridad", "confianza", "luminosidad"],
  prohibitedWords: ["barato", "urgente", "mágico"],
  audience: "Profesionales y adultos jóvenes preocupados por salud y estética",
  country: "España",
  language: "Español",
  copyRules: ["Hablar en primera persona", "Priorizar beneficios concretos", "Evitar exageraciones"],
  legalNotes: ["No hacer promesas médicas", "Incluir información de ingredientes"],
};
